### PR TITLE
Adjust firewall script for El Capitan

### PR DESCRIPTION
**Pull request by ctborg**
* Drops anchor in pf
* Resolves issue #507

### CODE REVIEW

**Comment by stereodenis** [comment]
:+1:

**Comment by mrsweaters** [comment]
Woo!

**Comment by jsmestad** [comment]
:+1:

**Comment by ggamel** [comment]
:+1: Please merge if this resolve #507.

**Comment by matthutchinson** [comment]
This fixed things for me too :+1:

**Comment by jeremy** [comment]
Does this work on Mavericks / Yosemite as well, or is the anchor required there?

**Comment by ctborg** [comment]
This PR is obsolete.  This change was only required for El Cap Public Beta 1.

**Pull request closed without merging**
